Resto\MainBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Resto\MainBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '40'
        password:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        tel:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
