parameters:
#    pussy_patrol_main.example.class: PussyPatrol\MainBundle\Example

services:
#    pussy_patrol_main.example:
#        class: %pussy_patrol_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
