<?php

namespace Resto\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends EntityRepository
{
}
