resto_main_homepage:
    pattern:  /
    defaults: { _controller: RestoMainBundle:Resto:index }

resto_theme:
    pattern: /theme/{themeid}
    defaults: { _controller: RestoMainBundle:Resto:theme }
    requirements:
        themeid: \d+
