resto_homepage:
    pattern:  /
    defaults: { _controller: RestoMainBundle:Resto:index }

resto_theme:
    pattern: /theme/{themeid}
    defaults: { _controller: RestoMainBundle:Resto:theme, themeid: -1 }
    requirements:
        themeid: \d*

resto_resto:
    pattern: /resto/{restoid}
    defaults: { _controller: RestoMainBundle:Resto:resto }
    requirements:
        restoid: \d+

resto_panier:
    pattern: /panier/
    defaults: { _controller: RestoMainBundle:Resto:panier }

resto_ajoute_article:
    pattern: /ajouteArticle/{id}/{quantite}
    defaults: { _controller: RestoMainBundle:Resto:panier }
    requirements:
        id: \d+
        quantite: \d+

resto_user:
    pattern: /user/{userid}
    defaults: { _controller: RestoMainBundle:Resto:user }
    requirements:
        userid: \d+



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile